name: CI-CD-front

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.7

      - name: Set up Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: ${{ vars.NODE_VERSION }}  
          
      - name: Install dependencies
        run: yarn install

      - name: Build project with Vite
        run: yarn build

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4.3.3
        with:
          name: build-artifacts
          path: ${{ vars.BUILD_PATH }}
          retention-days: ${{ vars.RETENTION_DAYS }}

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.7

      - name: Download production artifacts
        uses: actions/download-artifact@v4.1.7
        with:
          name: build-artifacts
          path: ${{ vars.BUILD_PATH }}  

      - name: Azure Static Web Apps Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: ${{ vars.BUILD_PATH }}
          azure_static_web_apps_api_token: ${{secrets.TOKEN_STATIC_WEBAPP}}
