name: CI-CD-front

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.7

      - name: Set up Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: '20.x'  
          
      - name: Install dependencies
        run: yarn install

      - name: Compile TypeScript
        run: npm run build

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4.3.3
        with:
          name: build-artifacts
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download production artifacts
        uses: actions/download-artifact@v4.1.7
        with:
          name: build-artifacts
          path: .  

      - name: Deploy React to GitHub Pages
        uses: bitovi/github-actions-react-to-github-pages@v1.2.4
        with:
          install_command: yarn install
          build_command: npm run build

  
